version: '3'
services:
  react_app:
    container_name: react_app
    build:
      context: ../dep-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - java_app
    volumes:
      - ../dep-react:/usr/src/app  # Ruta al proyecto en el host
      - node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install --legacy-peer-deps && npm run dev"

  java_app:
    container_name: java_app
    build:
      context: .
    ports:
      - "8092:8092"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/departamentoinformatica
      - DATABASE_USERNAME=julian519
      - DATABASE_PASSWORD=aelita607
    depends_on:
      - java_db
    volumes:
      - ./path/to/local/java_app:/usr/src/app  # Ajusta esta ruta al proyecto en el host
      - java_app_data:/usr/src/app/data  # Ajusta la ruta en el contenedor

  java_db:
    container_name: java_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Black607@
      MYSQL_DATABASE: departamentoinformatica
      MYSQL_USER: julian519
      MYSQL_PASSWORD: aelita607
    volumes:
      - java_db_data:/var/lib/mysql

volumes:
  node_modules:
  java_app_data:
  java_db_data:
