# Establecer la imagen base de Node.js
FROM node:20.12.2

# Crear y establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar los archivos de la aplicación
COPY package.json .
COPY package-lock.json .

# Instalar las dependencias
RUN npm install
RUN npm install vite -g

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto usado por Vite
EXPOSE 5173

RUN npm run dev
RUN node server.js